### ISSUE TITLE
მონაცემთა ბაზა

### ISSUE THREAD

**Issue by RaZma07** [GeoLabCommunity/geolab-final-project-TeacherWebsite#1]
Announcement 
- ID
- Title
- Description
- Add Data
- price_per_month
- lessons_per_month
- Image Name
- User ID

User Profile
- ID
- email
- Password
- First Name
- Last Name
- Address
- Phone #
- Registration Date
- About Me
- Age
- Gender
- Profile Picture
- City ID

Cities
- city_id
- name

**Comment by maxuna14** [comment]
Done
